### ISSUE TITLE
html/css navigates you to the wrong section

### ISSUE THREAD

**Issue by nanashiW** [march08/animated-burgers#2]
Under 'Available as plain html/css or as React components', if you click on html/css, it takes you to react section instead as it is using the incorrect id, it should be finding **#htmlcss**.

**Comment by march08** [comment]
Code is fine [here](https://github.com/march08/animated-burgers/blob/master/packages/preview/src/App/index.js#L95), generated html with react-snap is ok as well, probably some issue with hydrating? Need to check.
