### ISSUE TITLE
Cannot get to work 

### ISSUE THREAD

**Issue by JamesRobionyRogers** [march08/animated-burgers#35]
Needless to say, I cannot get this to work. 

I've followed the instruction on the website:

1. Added the div block 
2. Changed the class to the appropriate one 
3. Copied the CSS file into my folders and linked them in the head of the HTML
4. Even added and linked the JS. Although do not believe this does anything but was worth a try 

So my problem is that I cannot trigger the animation at all. I've even tried it in a brand new document with no success. Same with codepen, no success there either. I've even tried using developer tools on the website to try and figure it out, but of cause, I would not be here if I did solve my problem. 

I know the CSS is working because I can see the lines, so it can't be a problem with linking the file.

**Comment by Deep-Codes** [comment]
Was it React or Normal Vanilla JS because it works in my React/Gatsby Project...
