### ISSUE TITLE
Unable to use it on create-react-app

### ISSUE THREAD

**Issue by ManudeQuevedo** [march08/animated-burgers#4]
I'm having difficulties when using it on my React app, when trying to install the npm or yarn package it displays the following error message:

`npm install --save @animated-burgers/{burger-style} classnames
npm ERR! code ENOLOCAL
npm ERR! Could not install from "@animated-burgers/{burger-style}" as it does not contain a package.json file.
npm ERR! A complete log of this run can be found in:`

I would truly appreciate if you could tell me a way for using it on ReactJS.

Thanks in advance!

**Comment by ManudeQuevedo** [comment]
It was a mistake of mine! Re-read the instructions and found where the issue was!

**Comment by march08** [comment]
@ManudeQuevedo glad you found it, i might want to write it more clear then!
